/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Controllers.LoginControllers;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;



/**
 *
 * @author hamlet
 */
public class Dashboard extends javax.swing.JFrame {

    /** Creates new form Dashboard */
    
    
    String username = LoginControllers.arrUser.get(0).getFullname();
    String roles = LoginControllers.arrUser.get(0).getRoles();    
    
    public Dashboard() {
        initComponents();
        btnLowonganku.setVisible(false);
        setDashboard();                
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        jBtnLamar = new javax.swing.JButton();
        jBtnKerja = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnLowonganku = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setText("Dashboard");

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setText("Hello ,");

        lblUsername.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblUsername.setText("Username");

        jBtnLamar.setText("Lihat Lamaran");
        jBtnLamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLamarActionPerformed(evt);
            }
        });

        jBtnKerja.setText("Cari Kerja");
        jBtnKerja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKerjaActionPerformed(evt);
            }
        });

        jButton3.setText("Lihat Biodata");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnLowonganku.setText("Lowonganku");
        btnLowonganku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLowongankuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel1)
                .addGap(41, 154, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 325, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnLamar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnKerja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLowonganku, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(133, 133, 133))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblUsername)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jBtnKerja)
                .addGap(18, 18, 18)
                .addComponent(jBtnLamar)
                .addGap(18, 18, 18)
                .addComponent(btnLowonganku)
                .addGap(23, 23, 23)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //BTN LIHAT PELAMAR DAN     
    private void jBtnLamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLamarActionPerformed
        if(roles.equals("employeer") || roles.equals("admin")){
//            LIHAT PELAMAR UNTUK ADMIN HRD
            try {
                LamarForm join;
                join = new LamarForm();
                join.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
            }                        
        }else{
//            LIHAT LAMARANKU UNTUK JOBSEEKER
             
            try {
                Lamaranku lm = new Lamaranku();
                lm.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        
    }//GEN-LAST:event_jBtnLamarActionPerformed
    
    //BTN KERJA DAN BTN TAMBAH LOWONGAN
    private void jBtnKerjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKerjaActionPerformed
        if(roles.equals("employeer") || roles.equals("admin")){
//          TAMBAH KERJA UNTUK ADMIN HRD
            TambahLowonganForm lf;
            lf = new TambahLowonganForm();
            lf.setVisible(true);
        }else{
//          CARI KERJA UNTUK ADMIN HRD
            try {
                LamarForm join;
                join = new LamarForm();
                join.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
            }    
        }
        
        
    }//GEN-LAST:event_jBtnKerjaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        LoginForm lf;
        try {
            lf = new LoginForm();
            lf.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        BiodataForm biodataForm = new BiodataForm();
        biodataForm.setVisible(true);        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnLowongankuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLowongankuActionPerformed
         
        try {
            Lowonganku lw = new Lowonganku();
            lw.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnLowongankuActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLowonganku;
    private javax.swing.JButton jBtnKerja;
    private javax.swing.JButton jBtnLamar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
    
    private void setDashboard(){
        lblUsername.setText(username);
        if(roles.equals("employeer")){
            jBtnLamar.setText("Lihat Pelamar");
            jBtnKerja.setText("Tambah Lowongan");
            btnLowonganku.setVisible(true);
        }
        
    }
}
