/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controllers.DataControllers;
import Controllers.LoginControllers;
import Models.Jobjoin;
import Models.Joblist;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hamlet
 */

//FORM UNTUK PELAMAR dan MELAMAR


public class LamarForm extends javax.swing.JFrame {
    private final DataControllers dc;
    
    DefaultTableModel dtmJoblist = new DefaultTableModel(new String[]{"ID","Nama Pekerjaan","Gaji","Lokasi"},0);
    DefaultTableModel dtmJobjoin = new DefaultTableModel(new String[]{"ID","Nama Pelamar","Nama Pekerjaan"},0);
    String role = LoginControllers.arrUser.get(0).getRoles();
    
    public LamarForm() throws SQLException {
        initComponents();
        
        this.dc = new DataControllers();
        this.showTableJobjoin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnLamar = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnLamar.setText("Lamar");
        btnLamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamarActionPerformed(evt);
            }
        });

        btnClose.setText("<- Back");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClose)
                        .addGap(220, 220, 220)
                        .addComponent(btnLamar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLamar)
                    .addComponent(btnClose))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnLamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamarActionPerformed
                
        if(role.equals("jobseeker")){
            String idjobseeker = LoginControllers.arrUser.get(0).getId_jobseeker().toString();
            String id = dtmJoblist.getValueAt(jTable1.getSelectedRow(),0).toString();
            try {
            dc.joinJob(id, idjobseeker);
            JOptionPane.showMessageDialog(this,"Berhasil melamar pekerjaan");
        } catch (Exception e) {
            System.err.println("e");
            JOptionPane.showMessageDialog(this,"Error : "+ e);
        }
        }
        
        
    }//GEN-LAST:event_btnLamarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LamarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LamarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LamarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LamarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LamarForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnLamar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
    private void showTableJobjoin() throws SQLException{
        
        if(role.equals("employeer") || role.equals("admin")){
            btnLamar.setVisible(false);                        
            dtmJobjoin.setRowCount(0);
            String idemployeer = LoginControllers.arrUser.get(0).getId_employeer().toString();
            
            for(Jobjoin p : this.dc.getJoinJob(idemployeer)){
                System.out.println(p.getId_jobjoin());
                System.out.println(p.getNameJobseeker());
                System.out.println(p.getNameJob());
                dtmJobjoin.addRow(new String[]{ p.getId_jobjoin().toString() , p.getNameJobseeker() , p.getNameJob()  });
            }
            jTable1.setModel(dtmJobjoin);
        }else{            
            dtmJoblist.setRowCount(0);
            for(Joblist p : this.dc.getlistJob()){
                dtmJoblist.addRow(new String[]{ p.getId_job().toString() , p.getJobname() , p.getJobsalary().toString() , p.getJoblocation()  });            
            }
            jTable1.setModel(dtmJoblist);
        
        }
        
    }

}
